[package]
name = "among-us-discord-bot"
version = "0.1.0"
authors = ["Blake Wyatt <blakewy@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.2"
tokio = "0.2.22"
chrono = "0.4.19"